on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Test
      run: cargo test
    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Format
      run: cargo fmt --all -- --check
    - name: Check
      run: cargo check
